plugins:
  - '@trivago/prettier-plugin-sort-imports'
trailingComma: 'es5'
tabWidth: 2
semi: true
singleQuote: true
importOrder:
  - '^next(.*)'
  - '^react(.*)'
  - '<THIRD_PARTY_MODULES>'
  - '^@/components/(.*)'
  - '^@/components/ui/(.*)'
  - '^@/(.*)'
  - '^.(.?)/(.*)'
  - '^./(.*)\.css'
importOrderSeparation: true
importOrderSortSpecifiers: true
