import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';

import { cn } from '@/lib/utils';

import './globals.css';

const raleway = Raleway({ weight: '500', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'bg-slate-50 tracking-[0.4px] text-sm',
          raleway.className
        )}
      >
        {children}
      </body>
    </html>
  );
}
